# -*- coding: utf-8 -*-
"""Kafka-consumer.ipynb

Automatically generated by Colab Abhijit Challapalli.

Original file is located at
    https://colab.research.google.com/drive/1nZAmRVzB8SX9Qfh8RXCHjN7vprndizDL
"""

#pip install kafka-python

#pip install s3fs

#pip install boto3

import pandas as pd
from kafka import KafkaConsumer,KafkaProducer
from time import sleep
from json import dumps,loads
import json
from s3fs import S3FileSystem

consumer = KafkaConsumer('demo',bootstrap_servers=['your_public_aws_domain:9092'],value_deserializer=lambda x: loads(x.decode('utf-8')))

s3=S3FileSystem(key='your_key',secret='your_secret_key')

for count,i in enumerate(consumer):
  with s3.open("s3://stock-market-kafka-analysis-abhi/stock_mkt{}.json".format(count),'w') as file:
    json.dump(i.value,file)