# -*- coding: utf-8 -*-
"""Kafka-producer.ipynb

Automatically generated by Colab Abhijit Challapalli.

Original file is located at
    https://colab.research.google.com/drive/1VBQltUWy1Cb19l5PBG1vVjT-CrBptpOL
"""

#pip install kafka-python

import pandas as pd
from kafka import KafkaConsumer,KafkaProducer
from time import sleep
from json import dumps
import json

producer=KafkaProducer(bootstrap_servers=['your_public_aws_domain:9092'],value_serializer=lambda x: dumps(x).encode('utf-8'))

producer.send('demo',value="is it working")

df=pd.read_csv("/content/drive/MyDrive/Extracted.csv")

df.head(5)

while True:
  dict_stock=df.sample(1).to_dict(orient="records")[0]
  producer.send('demo',value=dict_stock)